### DISCUSSION TITLE
Can i  pass file name as arg to  script?

### DISCUSSION THREAD

**Discussion by borsemayur2** [jurassiscripts/velociraptor#55] [Q&A] [answered]
```yaml
allow:
  - net
scripts:
  demo: deno run [PASSED_ARG]  # vr demo app.ts
```
how can I achieve this?

**Comment by umbopepato** [comment, marked as answer]
Hi @borsemayur2!

`vr run` arguments are [forwarded to your scripts](https://github.com/jurassiscripts/velociraptor#running-scripts), so you can simply write:

```yaml
allow:
  - net
scripts:
  demo: deno run
```

and run

```shell
$ vr demo app.ts
```

The resulting command will be:

```shell
$ deno run app.ts
```
