### DISCUSSION TITLE
Suggestion: accept `tsconfig` parameter for `deno fmt` and `deno lint`

### DISCUSSION THREAD

**Discussion by reosablo** [jurassiscripts/velociraptor#95] [Ideas]
Since Deno 1.14, `deno fmt` and `deno lint` accepts `--config` parameter.

[Configuration file (deno.land/manual)](https://deno.land/manual/getting_started/configuration_file)

I wrote `scripts.yaml` like the bellow but the `tsconfig` parameters are ignored. I expected they accept that.

```yaml
scripts:
  fmt:
    cmd: deno fmt
    tsconfig: deno.jsonc
  lint:
    cmd: deno lint
    tsconfig: deno.jsonc
```

I'm using `velociraptor@1.3.0` version.
