### ISSUE TITLE
Feature request: Allow passing a `config` setting in the scripts file

### ISSUE THREAD

**Issue by saadq** [jurassiscripts/velociraptor#103]
Deno now supports passing a `--config` flag to its CLI for customizing the builtin compiler/linter/formatter with a configuration file: https://deno.land/manual@v1.16.3/getting_started/configuration_file. I tried looking through the [`DenoCliOptions`](https://doc.deno.land/https/deno.land/x/velociraptor/src/scripts_config.ts#DenoCliOptions), but it doesn't seem like this is currently supported.

To use this, currently I have a config file:

**deno.json**
```json
{
  "fmt": {
    "options": {
      "singleQuote": true
    }
  }
}
```

**velociraptor.yaml**
```yaml
scripts:
  lint:
    cmd: deno lint --config=deno.json
    desc: Lints the code using Deno's standard linter

  format:
    cmd: deno fmt --config=deno.json
    desc: Formats the code using Deno's standard formatter
```

It would be nice if we could specify our config file the same way we could specify files for `lock`/`imap`/`envFile`. Perhaps something like:

**velociraptor.yaml**
```yaml
configFile: deno.json

scripts:
  lint:
    cmd: deno lint
    desc: Lints the code using Deno's standard linter

  format:
    cmd: deno fmt
    desc: Formats the code using Deno's standard formatter
```
