### ISSUE TITLE
inspect and inspectBrk should also accept true

### ISSUE THREAD

**Issue by DerZade** [jurassiscripts/velociraptor#106]
Deno allows using the CLI options `--inspect` / `--inspect-brk`  without specifying an IP & port.

It would be nice to just use `true` within the config:
```yml
#scripts.yml
scripts:
  start:
    cmd: main.ts
    inspect: true
```
