### ISSUE TITLE
Problem: Env Interpolation in Scripts

### ISSUE THREAD

**Issue by bjesuiter** [jurassiscripts/velociraptor#115]
I use the following script definitions (simplified for shortness): 

```
envFile:
  - .env
  
scripts:
  install: 
    cmd: deno install --name ${CLI_NAME} main.ts 
    allow: 
      read: true
      run: true
      net: 'deno.land,x.nest.land'
```

## Problem

CLI_NAME is empty on windows in this setting 

## Wanted Behavior 

CLI_NAME contains the right content as loaded from .env and is correctly interpolated for running the command
