### ISSUE TITLE
Any plan to make a GitHub action to setup velociraptor ?

### ISSUE THREAD

**Issue by lowlighter** [jurassiscripts/velociraptor#44]
It would be nice if we could setup velociraptor easily in workflows with : 

```yml
- name: Setup Deno
  uses: denolib/setup-deno@v2
- name: Setup Velociraptor
  uses: jurassiscripts/setup-velociraptor 
  #run: deno install -qA -n vr https://deno.land/x/velociraptor@1.0.0-beta.17/cli.ts
```
