### ISSUE TITLE
PermissionDenied for denon cmd

### ISSUE THREAD

**Issue by borsemayur2** [jurassiscripts/velociraptor#45]
Below config works with `deno run mod.ts` command but fails for `denon run mod.ts` command

Versions:
deno: 1.8.1
denon: v2.4.7
velociraptor: v1.0.0-beta.17

```
allow:
  - net

scripts:
  start: 
    cmd: denon run mod.ts  # deno run mod.ts works
    allow:
      net: 127.0.0.1

```

**Comment by umbopepato** [comment]
Hey @borsemayur2, thanks for opening this issue!
This is the intended behavior: vr only recognizes `deno` calls to inject permissions and other options. However, you could use the [`watch`](https://github.com/jurassiscripts/velociraptor#watch) option to reload on file changes:

```yaml
scripts:
  start: 
    cmd: mod.ts
    watch: true
    allow:
      net: 127.0.0.1
```
