### ISSUE TITLE
Can you specify an envFile for each script?

### ISSUE THREAD

**Issue by antoniogamiz** [jurassiscripts/velociraptor#50]
It could be useful to have a development envfile and another for production.

**Comment by umbopepato** [comment]
Hey @antoniogamiz, you mean something like this?

```yaml
scripts:
  dev:
    envFile: .env.dev
    # ...

  prod:
    envFile: .env.prod
    # ...
```

This is already possible, see [here](https://github.com/jurassiscripts/velociraptor#environment-variables)
