### ISSUE TITLE
Import map diagnostics:   - Invalid top-level key "hash". Only "imports" and "scopes" can be present.

### ISSUE THREAD

**Issue by borsemayur2** [jurassiscripts/velociraptor#56]
Getting the message after adding `imap: import_map.json` in `scripts.yaml` file. The app runs though.
```yaml
  dev:
    cmd: deno run src/mod_json.ts
    allow:
      - read
      - write
    watch: true
    unstable: true
    imap: import_map.json
```

Deno: 1.9.0
Velociraptor: 1.0.0-beta.18
